# Generated by Django 4.1.1 on 2022-09-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_remove_entry_authors_remove_entry_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_name',
            new_name='roll_no',
        ),
    ]
