# Generated by Django 4.1.1 on 2022-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
