# Generated by Django 4.1.1 on 2022-09-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_admission_date_student_pass_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pass_date',
        ),
    ]
